from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
import os
from flask_login import login_required, current_user
from . import db

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)


@main.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_file():
    if request.method == 'POST':
        if 'image_file' not in request.files:
            return 'There is no Image in the request.'
        img = request.files['image_file']
        path = os.path.join(f"{current_app.config.get('UPLOAD_FOLDER')}/{current_user.name}/")
        os.makedirs(path, exist_ok=True)
        img.save(path + img.filename)

        # For now it redirects to profile, later it will go to the image's autogenerated transformations
        return render_template('profile.html')

    return render_template('image_form.html')


@main.route('/gallery', methods=['GET'])
@login_required
def view_gallery():
    images_folder = f"{current_app.config.get('UPLOAD_FOLDER')}/{current_user.name}/"
    return render_template('gallery.html', images_folder=images_folder)
